homework1
paulrainy/rubybasics pull request #1
Opened 2023-01-06 11:40 UTC by paulrainy

2023-01-08 21:23 UTC, Starlexxx requested changes

2023-01-08 21:23 UTC, Starlexxx commented on task1/task1.rb
> +  person_name = gets
```ruby
person_name = gets.chomp
```
Чтобы автоматом убрать все пробелы и тд из строки https://apidock.com/ruby/String/chomp

2023-01-08 21:23 UTC, Starlexxx commented on task1/task1.rb
> +  if person_perfect_weight < 0
```ruby
if person_perfect_weight.negative?
```
лучше исполльзовать методы negative? positive? zero? так лучше читается

2023-01-08 21:23 UTC, Starlexxx commented on task1/task2.rb
> +  puts "the area of triangle is #{s}"
А если пользователь введет отрицательные числа?)

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +
лишняя строчка

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +  g = [a, b, c].max
неплохо, только назови переменную получше)

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +    if a * a == b * b + c * c
Все условия лучше вынести в отдельные функции, возвращающие bool и понятно их назвать и передавать в них самую длинную сторону

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +      puts "it's a right triangle!"
эти два puts'а повторяются много раз, надо вынести в функцию и передовать туда гипотенузу

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +      versatile_check(a, b, c)
подумай, как убрать повторяющийся код

2023-01-08 21:23 UTC, Starlexxx commented on task1/task3.rb
> +    # this else isn't working idk why
убери, если хочешь разобраться, почему не вызывается -- пройдись отладчиком

2023-01-08 21:23 UTC, Starlexxx commented on task1/task4.rb
> +    puts "ur root: x = #{x}"
лишний код. про метод ```zero?``` уже писал выше

2023-01-08 21:23 UTC, Starlexxx commented on task1/task4.rb
> +  end
в ```main``` все должно быть максимально просто никаких огромных ветвлений. Выноси все в отдельные функции

2023-01-09 14:43 UTC, paulrainy commented on task1/task3.rb
> +  g = [a, b, c].max
Да, назову просто гипотенузой на англ

2023-01-09 19:18 UTC, Starlexxx approved these changes

2023-01-09 19:19 UTC, merged