homework-2
paulrainy/rubybasics pull request #2
Opened 2023-01-30 15:56 UTC by paulrainy

💀

2023-01-30 17:17 UTC, Starlexxx requested changes

2023-01-30 17:17 UTC, Starlexxx commented on task2/task1.rb
> +  list = { 'January' => 31, 'February' => 28, 'March' => 31, 'April' => 30, 'May' => 31, 'June' => 30, 'July' => 31,
Используй пж современную запись без хэшрокета. И вынеси это в константу
```ruby
MONTHS = { 
  january: 31,
  february: 28,
  march: 31,
  april: 30,
  may: 31,
  june: 30,
  july: 31,
  august: 31,
  september: 30,
  october: 31,
  november: 30,
  december: 31,
}
```

2023-01-30 17:17 UTC, Starlexxx commented on task2/task1.rb
> +  list.each_pair { |key, value| puts key if value == 30 }
Хорошо, но можно лучше)
```ruby
each_pair { |month, days| puts month if days == 30 }
```
Кста .each == .each_pair и в этом случае мне нравится, что ты используешь именно each_pair)

2023-01-30 17:17 UTC, Starlexxx commented on task2/task2.rb
> +  puts array
Тотально императивное мышление)
Лучше 
```ruby
puts (10..100).step(5).map(&:to_i)
```

2023-01-30 17:17 UTC, Starlexxx commented on task2/task3.rb
> +  puts fib_array
```ruby
array = [0, 1]

loop do
  latest_num = array.last + array[-2]
  break unless latest_num < 100

  array.push latest_num
end

array.delete_at(1)
```

2023-01-30 17:17 UTC, Starlexxx commented on task2/task4.rb
> +  vowel_hash_letters.each_pair { |letter, number| puts "#{letter} is #{number}" }
Перемудрил 
```ruby
vowels_hash = {}
vowels = %w[a e i o u y]

('a'..'z').each.with_index { |letter, i| vowels_hash[letter] = i if vowels.include? letter }

puts vowels_hash
```

2023-01-30 17:17 UTC, Starlexxx commented on task2/task5.rb
> +  false
```ruby
def leap?(year)
  return true if ((year % 400).zero? || year % 100 != 0) && (year % 4).zero?

  false
end
``` 
Так вроде работает и короче

2023-01-30 17:17 UTC, Starlexxx commented on task2/task5.rb
> +  month_hash = { 1 => 31, 2 => 28, 3 => 31, 4 => 30, 5 => 31, 6 => 30, 7 => 31, 8 => 30, 9 => 31, 10 => 30, 11 => 31,
Хэш тут избыточен, по индексу массива можно определить номер месяца

2023-01-30 17:17 UTC, Starlexxx commented on task2/task5.rb
> +  num_arr
Очень сильно намудрил, тут массив избыточен, пускай пользователь введет три переменные

2023-01-30 17:17 UTC, Starlexxx commented on task2/task5.rb
> +  answer + num_arr[0]
У нас есть дни, месяц и год. Сделаем массив month В котором лежат 31, 28, 31, 30 .... Если год вискоосный, то заменяем в нем 28 на 29.  Дальше юзаем магию:
```ruby 
(0..month - 2).each { |i| day += months[i] }
```
Вуаля, теперь в переменной, куда пользователь ввел дни лежат все дни этого года до текущего

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  name = gets.to_s.chomp
лишнее to_s пользователь всегда вводит строку

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  while name.size < 2 || name.include?(' ')
А если он купил "Яблоко зеленое" или Ежа)))
Убери эту проверку ты не на си пишешь

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  name
Вообще я бы тупо захуячил все в один цикл и ```while name != 'stop'```

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  end
Сделай через рекурсию, либо убери проверку

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  num
Пробел перед тем, что возвращает функция

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +  shop_list
Опять забыл пробел

2023-01-30 17:17 UTC, Starlexxx commented on task2/task6.rb
> +main
Добавь .idea/ в .gitignore https://git-scm.com/docs/gitignore

2023-01-31 09:54 UTC, paulrainy commented on task2/task5.rb
> +  false
Да, работает, проверил

2023-01-31 13:43 UTC, paulrainy commented on task2/task6.rb
> +  while name.size < 2 || name.include?(' ')
include? уберу, так как реально бред
А <2 оставлю, так как тот же "ёж" проходит проверку вполне

2023-01-31 13:55 UTC, paulrainy commented on task2/task6.rb
> +  name
Насколько понимаю, ты предлагаешь заменить loop на while
Ок

2023-02-06 10:08 UTC, Starlexxx commented on task2/task5.rb
> +  unless num.positive? && num <= 31
Если ты уж так ударился в проверки, то 31 -- не единственный возможный показатель. Рекомендую сделать метод ```month_days(month)``` он будет возвращать дни месяца)

2023-02-06 10:08 UTC, Starlexxx commented on task2/task5.rb
> +def spec_check(day, month_arr, month)
что означает навание этой функции? просто spec это обычно про тесты)

2023-02-07 14:45 UTC, Starlexxx approved these changes

2023-02-07 17:03 UTC, merged